
CREATE TABLE [dbo].[LIVRO] (
    [LIVROID]    INT            IDENTITY (1, 1) NOT NULL,
    [LITULO]     NVARCHAR (255) NOT NULL,
    [ISBN]       NVARCHAR (20)  NOT NULL,
    [QUANTIDADE] INT            NOT NULL,
    [STATUS]     NVARCHAR (20)  NOT NULL,
    [AUTORID]    INT			NOT NULL,
    [EDITORAID]  INT			NOT NULL,
    PRIMARY KEY CLUSTERED ([LIVROID] ASC),
    CONSTRAINT [FK_AUTORID] FOREIGN KEY ([AUTORID]) REFERENCES [dbo].[AUTOR] ([AUTORID]),
    CONSTRAINT [FK_EDITORID] FOREIGN KEY ([EDITORAID]) REFERENCES [dbo].[EDITORA] ([EDITORAID])
);

INSERT INTO LIVRO ([LITULO],[ISBN],[QUANTIDADE],[STATUS],[AUTORID],[EDITORAID]) 
VALUES ('Minha História','978-85-470-0064-6',100,'Disponível',3,3)

INSERT INTO LIVRO ([LITULO],[ISBN],[QUANTIDADE],[STATUS],[AUTORID],[EDITORAID]) 
VALUES ('O Ceticismo da Fé','124-85-470-4765-5',340,'Disponível',2,2)

INSERT INTO LIVRO ([LITULO],[ISBN],[QUANTIDADE],[STATUS],[AUTORID],[EDITORAID]) 
VALUES ('Meu Sonho','878-85-470-6476-1',1200,'Disponível',1,3)
