
CREATE TABLE [dbo].[LIVRO] (
    [LIVROID]    BIGINT         NOT NULL,
    [LITULO]     NVARCHAR (255) NOT NULL,
    [ISBN]       NVARCHAR (20)  NOT NULL,
    [QUANTIDADE] INT            NOT NULL,
    [STATUS]     VARCHAR (20)   NOT NULL,
    [AUTORID]    BIGINT         NOT NULL,
    [EDITORAID]  BIGINT         NOT NULL,
    PRIMARY KEY CLUSTERED ([LIVROID] ASC),
    CONSTRAINT [FK_AUTORID] FOREIGN KEY ([AUTORID]) REFERENCES [dbo].[AUTOR] ([AUTORID]),
    CONSTRAINT [FK_EDITORID] FOREIGN KEY ([EDITORAID]) REFERENCES [dbo].[EDITORA] ([EDITORAID])
);

