
CREATE TABLE [dbo].[AUTOR] (
    [AUTORID]   BIGINT        NOT NULL,
    [NOME]      NVARCHAR (20) NOT NULL,
    [SOBRENOME] NVARCHAR (20) NOT NULL,
    [IDADE]     INT           NULL,
    PRIMARY KEY CLUSTERED ([AUTORID] ASC)
);

