
CREATE TABLE [dbo].[EDITORA] (
    [EDITORAID]  BIGINT         NOT NULL,
    [NOME]       NVARCHAR (50)  NOT NULL,
    [CEP]        NVARCHAR (50)  NOT NULL,
    [ESTADO]     NVARCHAR (15)  NOT NULL,
    [PAIS]       NVARCHAR (50)  NULL,
    [LOGRADOURO] NVARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([EDITORAID] ASC)
);

