
CREATE TABLE [dbo].[EMPRESTIMO] (
    [EMPID]          INT           IDENTITY (1, 1) NOT NULL,
    [DATAEMPRESTIMO] DATETIME   NOT NULL,
    [DATADEVOLUCAO]  DATETIME   NOT NULL,
    [VALORMULTA]     MONEY		NULL,
    [LIVROID]        INT		NOT NULL,
    [ALUNOID]        INT		NOT NULL,
    PRIMARY KEY CLUSTERED ([EMPID] ASC),
    CONSTRAINT [FK_LIVRO] FOREIGN KEY ([LIVROID]) REFERENCES [dbo].[LIVRO] ([LIVROID]),
    CONSTRAINT [FK_ALUNO] FOREIGN KEY ([ALUNOID]) REFERENCES [dbo].[ALUNO] ([ALUNOID])
);

INSERT INTO EMPRESTIMO ([DATAEMPRESTIMO],[DATADEVOLUCAO],[VALORMULTA],[LIVROID],[ALUNOID]) 
VALUES (29/01/2020,10/02/2020,0.00,2,1)

INSERT INTO EMPRESTIMO ([DATAEMPRESTIMO],[DATADEVOLUCAO],[VALORMULTA],[LIVROID],[ALUNOID]) 
VALUES (04/02/2020,18/02/2020,0.00,5,2)
