
CREATE TABLE [dbo].[AUTOR] (
    [AUTORID]   INT           IDENTITY (1, 1) NOT NULL,
    [NOME]      NVARCHAR (20) NOT NULL,
    [SOBRENOME] NVARCHAR (20) NOT NULL,
    [IDADE]     INT           NULL,
    PRIMARY KEY CLUSTERED ([AUTORID] ASC)
);

INSERT INTO AUTOR([NOME],[SOBRENOME],[IDADE]) 
VALUES ('Ezekiel','Muxito','27')

INSERT INTO AUTOR([NOME],[SOBRENOME],[IDADE]) 
VALUES ('Rodrigo','Silva','41')

INSERT INTO AUTOR([NOME],[SOBRENOME],[IDADE]) 
VALUES ('Michelle','Obama','43')